### ISSUE TITLE
TF2 Support

### ISSUE THREAD

**Issue by rumblefrog** [bbennett905/store-aura#1]
Possible to add other game support, such as TF2?

**Comment by bbennett905** [comment]
I'll look into it. It shouldn't be too difficult, but I probably won't have time to do it for at least a week.

**Comment by rumblefrog** [comment]
Thanks!

**Comment by rumblefrog** [comment]
Any update on this?

**Comment by bbennett905** [comment]
Sorry it took so long, but it should work with the most recent commit. I haven't tested it though, let me know if there's any problems

**Comment by rumblefrog** [comment]
I'm getting this for some reason, all other modules work fine :P. I'm using Store 1.2 btw.

```
L 01/20/2017 - 23:21:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 01/20/2017 - 23:21:00: [SM] Blaming: store/store-backend.smx()
L 01/20/2017 - 23:21:00: [SM] Call stack trace:
L 01/20/2017 - 23:21:00: [SM]   [0] SQL_TQuery
L 01/20/2017 - 23:21:00: [SM]   [1] Line 1781, D:\SourcePawn\store\scripting\store-backend.sp::Store_Local_TQuery()
L 01/20/2017 - 23:21:00: [SM]   [2] Line 1355, D:\SourcePawn\store\scripting\store-backend.sp::GetEquippedItemsByType()
L 01/20/2017 - 23:21:00: [SM]   [3] Line 2256, D:\SourcePawn\store\scripting\store-backend.sp::Native_GetEquippedItemsByType()
L 01/20/2017 - 23:21:00: [SM]   [5] Store_GetEquippedItemsByType
L 01/20/2017 - 23:21:00: [SM]   [6] Line 200, E:\Server Files\store-aura\store-aura.sp::Event_PlayerSpawn()
```

**Comment by rumblefrog** [comment]
@bbennett905

**Comment by bbennett905** [comment]
I'll try to see if i can get a chance to test it out on TF2 soon, but it's possible that the problem is that you're still using 1.2.

**Comment by rumblefrog** [comment]
1.2 is the latest, no?

**Comment by bbennett905** [comment]
Sorry, my bad. Was thinking of something else, 1.2 is the latest.

**Comment by rumblefrog** [comment]
Lmk if I could do anything meanwhile.

**Comment by bbennett905** [comment]
Now that I've finally had some free time for this... I've made a bunch of changes with the most recent commit and I've tested it on TF2 using a clean install of Store 1.2 Final and SM 1.8.0. Everything should work as intended, although I don't believe there's any reasonable way to get custom particle support in TF2. You can use the default particle effects listed [here](https://developer.valvesoftware.com/wiki/List_of_TF2_Particles).
